### ISSUE TITLE
Cannot resolve all parameters for NavRegistry(?). Make sure they all have valid type or annotations.

### ISSUE THREAD

**Issue by vadimpopa** [driftyco/ionic2#456]
Any ideas why I get this error 
```javascript
NoAnnotationError {message: "Cannot resolve all parameters for NavRegistry(?). 
Make sure they all have valid type or annotations.", 
stack: "Error: Cannot resolve all parameters for NavRegist…i/provider.js:269:7
at Array.forEach (native)"}
```
at @App decorator:

```javascript
import "./app.css!";

import 'reflect-metadata'
import {App, IonicApp, Platform} from 'ionic/ionic';

import {HelloIonicPage} from './hello-ionic/hello-ionic';
import {ListPage} from './list/list';

@App({ // HERE ERROR IS THROWN
  templateUrl: 'app/app.html'
})

class MyApp {
  constructor(app: IonicApp, platform: Platform) {

    // set up our app
    this.app = app;
    this.platform = platform;
    this.initializeApp();

    // set our app's pages
    this.pages = [
      { title: 'Hello Ionic', component: HelloIonicPage },
      { title: 'My First List', component: ListPage }
    ];

    // make HelloIonicPage the root (or first) page
    this.rootPage = HelloIonicPage;
  }
```

full code here:
https://github.com/vadimpopa/jspm-ionic2-starter/tree/typescript

With es5/common code is working fine, only typescript code throws that error.

**Comment by tlancina** [comment]
Hmm strange, you aren't the first to report errors with jspm and typescript though.  How do I run your project with jspm?

**Comment by vadimpopa** [comment]
You have the full code here https://github.com/vadimpopa/jspm-ionic2-starter/tree/typescript.
I'm not sure though if it's an Ionic issue, but I didn't have any problems on Angular 2 decorators.

**Comment by tlancina** [comment]
Sure, but can you tell me what gulp tasks/jspm commands I need to run? There's nothing in the README

**Comment by vadimpopa** [comment]
Just added the basic in README.

**Comment by tlancina** [comment]
Great thanks, taking a look now.

**Comment by tlancina** [comment]
Thanks, this was a bug, should be fixed in https://github.com/driftyco/ionic2/commit/35159a4daa9d4391e3218743ce1c39f8722a9e92.  

Assuming you aren't using NavRegistry you can if you comment it out on line 60 of `jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/config/bootstrap.ts` as a temporary workaround.

**Comment by vadimpopa** [comment]
awesome, thanks

**Comment by vadimpopa** [comment]
Hmm btw have you notice this one ?, after you comment that line:
```javascript
ChangeDetectionError {_wrapperMessage: "TypeError: childAnimations[i].parent is not a function in [null]", _originalException: TypeError: childAnimations[i].parent is not a function
    at Animation.add (http://localhost:8080/j…, _originalStack: "TypeError: childAnimations[i].parent is not a func…ange_detection/abstract_change_detector.js:66:10)", _context: _Context, _wrapperStack: "Error: TypeError: childAnimations[i].parent is not…life_cycle.js:80:25↵    at Array.forEach (native)"…}_context: _ContextcomponentElement: ion-appcontext: MyAppelement: ion-menuexpression: nullinjector: Injectorlocals: Object__proto__: _Context_originalException: TypeError: childAnimations[i].parent is not a function
    at Animation.add (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/animations/animation.ts!transpiled:176:44)
    at new MenuRevealType (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu-types.ts!transpiled:99:31)
    at Menu._initType (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu.ts!transpiled:143:34)
    at Menu.onInit (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu.ts!transpiled:113:26)
    at AbstractChangeDetector.ChangeDetector_MyApp_0.detectChangesInRecordsInternal (eval at <anonymous> (unknown source), <anonymous>:41:70)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:92:12)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:75:10)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:142:12)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:79:10)
    at AbstractChangeDetector.detectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:66:10)_originalStack: "TypeError: childAnimations[i].parent is not a function↵    at Animation.add (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/animations/animation.ts!transpiled:176:44)↵    at new MenuRevealType (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu-types.ts!transpiled:99:31)↵    at Menu._initType (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu.ts!transpiled:143:34)↵    at Menu.onInit (http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.31/dist/src/typescript/components/menu/menu.ts!transpiled:113:26)↵    at AbstractChangeDetector.ChangeDetector_MyApp_0.detectChangesInRecordsInternal (eval at <anonymous> (unknown source), <anonymous>:41:70)↵    at AbstractChangeDetector.detectChangesInRecords (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:92:12)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:75:10)↵    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:142:12)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:79:10)↵    at AbstractChangeDetector.detectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:66:10)"_wrapperMessage: "TypeError: childAnimations[i].parent is not a function in [null]"_wrapperStack: "Error: TypeError: childAnimations[i].parent is not a function in [null]↵    at ChangeDetectionError.WrappedException [as constructor] (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/facade/exceptions.js:39:27)↵    at new ChangeDetectionError (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/exceptions.js:24:12)↵    at AbstractChangeDetector._throwError (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:240:15)↵    at AbstractChangeDetector.detectChangesInRecords (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:94:12)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:75:10)↵    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:142:12)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:79:10)↵    at AbstractChangeDetector.detectChanges (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/change_detection/abstract_change_detector.js:66:10)↵    at http://localhost:8080/jspm_packages/npm/angular2@2.0.0-alpha.44/src/core/life_cycle/life_cycle.js:80:25↵    at Array.forEach (native)"context: (...)location: nullmessage: (...)originalException: (...)originalStack: (...)wrapperMessage: (...)wrapperStack: (...)__proto__: __
```

**Comment by tlancina** [comment]
@vadimpopa Yep, fixed that one as well: https://github.com/driftyco/ionic2/commit/f8872a47b00906432ff0b6f55d37ae6ff151ccae.  Thanks! Our build process adds "strict mode" and that one was a weird one with the arguments object in non-strict mode.

There's another one after that: `Uncaught TypeError: Illegal invocation` that has to do with the way your app is being transpiled, but I didn't have a chance to dig into it completely yesterday and will be taking a look at today.

**Comment by tlancina** [comment]
@vadimpopa just a quick follow-up, it looks like you need to load `zone.js`, similar to how you are loading  `reflect-metadata` (import in app.ts).  This will patch requestAnimationFrame, and fix the `Illegal invocation` error.

**Comment by vadimpopa** [comment]
Hmm, will try that, initially I added "zone.js" in the angular2 app, without Ionic2, and at build or run I think I got a maximum call stack exceed because of dependencies resolve looping around "zone.js", but will check that once again. 

Thanks for your input.
