### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by ErikVanNorstrand** [driftyco/ionic2#483]
Version: Latest pull from npm install -g ionic@alpha

Steps to reproduce: 
1) npm install -g ionic@alpha
2) ionic start anyProjectName --v2
3) cd anyProjectName
4) ionic server

Error:

 ReferenceError: Promise is not defined
    at LazyResult.async (C:\Program Files\nodejs\node_modules\ionic\node_modules
\ionic-app-lib\node_modules\postcss\lib\lazy-result.js:152:31)
    at LazyResult.then (C:\Program Files\nodejs\node_modules\ionic\node_modules\
ionic-app-lib\node_modules\postcss\lib\lazy-result.js:75:21)
    at Object.processSass (C:\Program Files\nodejs\node_modules\ionic\node_modul
es\ionic-app-lib\lib\v2\transpile.js:211:4)
    at Object.serve (C:\Program Files\nodejs\node_modules\ionic\node_modules\ion
ic-app-lib\lib\v2\serve.js:53:17)
    at C:\Program Files\nodejs\node_modules\ionic\lib\ionic\serve.js:87:15
    at _fulfilled (C:\Program Files\nodejs\node_modules\ionic\node_modules\q\q.j
s:787:54)
    at self.promiseDispatch.done (C:\Program Files\nodejs\node_modules\ionic\nod
e_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Program Files\nodejs\node_modules\ion
ic\node_modules\q\q.js:749:13)
    at C:\Program Files\nodejs\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Program Files\nodejs\node_modules\ionic\node_modules\q\q.js:108
:17)

**Comment by ErikVanNorstrand** [comment]
A note on this bug, it only happens using the V2 templates. The V1 templates work fine.

**Comment by jbavari** [comment]
@ErikVanNorstrand What version of the CLI?

**Comment by ErikVanNorstrand** [comment]
Should I be using Ionic@Alpha or Ionic Framework?

Also, what command do you want me to run to get the CLI information?

**Comment by ErikVanNorstrand** [comment]
The ionic cli is version 2.0.0-alpha.18

That is installed with npm install -g ionic@alpha

**Comment by jbavari** [comment]
> Should I be using Ionic@Alpha or Ionic Framework?

To clarify, `ionic@alpha` is the Node command line interface, installing the `alpha` tagged version.

Ionic Framework is the HTML/JS components that you use to create pages.

With that said, please try the latest Ionic CLI, alpha.23 (`npm install -g ionic@alpha`) and let us know if that still gives you the issue.

**Comment by germgerm** [comment]
I just ran into this issue with ionic 1.1.1  on android 4.4.2 - same app installed on 5.1.1 does not encounter this error

Promise is not defined
    at file:///android_asset/www/js/bundle.js:5156:25
    at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23399:28)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23415:27
    at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24678:28)
    at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24489:31)
    at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24783:24)
    at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19196:47)
    at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19368:7)
    at XMLHttpRequest.requestLoaded (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19309:9)

**Comment by tlancina** [comment]
@germgerm what is the output of `ionic info` and where is that bundle coming from?

The recommended way to build for V2 is to use `ionic start` and then `ionic serve` to bundle your app using webpack: http://ionicframework.com/docs/v2/getting-started/tutorial/

**Comment by tlancina** [comment]
Ah it looks like you're using Ionic 1, this is the repo for Ionic 2 :), you can open an issue here: https://github.com/driftyco/ionic/issues.

**Comment by germgerm** [comment]
oops - sorry about that - found the thread googling - didn't check the actual forum

**Comment by tlancina** [comment]
Closing this as I believe it's no longer an issue, please reopen if that's not the case.

**Comment by gsanjeevkumar** [comment]
this continues to happen. please do not close.

**Comment by mhartington** [comment]
@gsanjeevkumar can you please provide the output from your `ionic info`

**Comment by tlancina** [comment]
@gsanjeevkumar for the latest CLI version you can track the issue here: https://github.com/driftyco/ionic2/issues/752.
