### ISSUE TITLE
docs/bug: Modals is not working

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#484]
Followed docs here http://ionicframework.com/docs/v2/components/#modals but a modal is not showing. No errors in console.

In docs demo I see there is a `<ion-overlay><script></script></ion-overlay>` element on the rendered page that is missed in my app.

Should I add the `<ion-overlay></ion-overlay>` somewhere as is in `app.html` in the demo? I am using tab pages starter. Tried to add to index.html without success. Probably should try the tabs template.

By the way `ActionSheets` is working fine.

I suggest to log an error to console when opening a modal and `<ion-overlay>` element is not presented.

=== app.html from demo - overlay at the bottom ===
```
<img src="img/android-statusbar-blue.png" style="display:none" id="md-only">
<img src="img/ios-statusbar.png" style="display:none" id="ios-only">


<ion-menu [content]="content" id="leftMenu">

  <ion-toolbar primary>
    <ion-title>Menu</ion-title>
  </ion-toolbar>

  <ion-content>

    <ion-list>

      <button ion-item *ng-for="#p of pages" (click)="openPage(p)">
        {{p.title}}
      </button>

      <button ion-item menu-close="leftMenu" detail-none>
        Close Menu
      </button>

    </ion-list>
  </ion-content>

</ion-menu>

<ion-nav id="nav" [root]="rootPage" #content></ion-nav>

<ion-overlay></ion-overlay>
```

**Comment by brandyscarney** [comment]
Yes you currently need to add `<ion-overlay></ion-overlay>` for the modal, we are working on removing this requirement. There is an issue here for it: https://github.com/driftyco/ionic2/issues/313

**Comment by astec** [comment]
In meantime it would be good to mentioned that at docs for Modals and other components relying on it - it's quite confusing at the moment.

**Comment by astec** [comment]
I tried to add `<ion-overlay></ion-overlay>` to tabs.html like this:
```html
<ion-tabs>
	<ion-tab tab-title="Contacts" tab-icon="chatbubbles" [root]="ContactsRoot"></ion-tab>
	<ion-tab tab-title="Pulse" tab-icon="pulse" [root]="DashRoot"></ion-tab>
	<ion-tab tab-title="Settings" tab-icon="cog" [root]="AccountRoot"></ion-tab>
</ion-tabs>
<ion-overlay></ion-overlay>
```
it gives a black screen above page tabs and error in console log:
```
TypeError: this.directive_2_0.onInit is not a function
    at AbstractChangeDetector.ChangeDetector_ContactsRoot_0.detectChangesInRecordsInternal (eval at <anonymous> (http://localhost:8100/build/js/app.bundle.js:20726:17), <anonymous>:22:70)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:8100/build/js/app.bundle.js:20180:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:20157:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8100/build/js/app.bundle.js:20245:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:20161:15)
    at AbstractChangeDetector._detectChangesInLightDomChildren (http://localhost:8100/build/js/app.bundle.js:20238:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:20158:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8100/build/js/app.bundle.js:20245:19)
    at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:20161:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8100/build/js/app.bundle.js:20245:19)
```

If I add it to app.html like below no errors in log but modal is not showing.
```
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Ionic</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link href="build/css/app.css" rel="stylesheet">
</head>

<body>
  <ion-app><ion-overlay></ion-overlay></ion-app>
  <script src="cordova.js"></script>
  <script src="build/js/app.bundle.js"></script>
</body>

</html>
```

This is based on the tabs starter (2nd tab if it matter).

**Comment by adamdbradley** [comment]
For now it needs to go in the root component: https://github.com/driftyco/ionic2-starter-tabs/blob/master/www/app/app.js#L6

Like so:
`<ion-nav [root]="root"></ion-nav><ion-overlay></ion-overlay>`

**Comment by astec** [comment]
@adamdbradley that worked for me, thanks. Would be cool if you add this to docs for Modal and probably updated all starters to have the overlay by default?
