### ISSUE TITLE
NavController: popToRoot() & popTo() are failing, back button is OK

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#511]
On a 3d screen I try to navigate to 1st page.

**For `this.nav.popToRoot()`:**
```
at: return this._popTo(this.first(), opts);

TypeError: this._popTo is not a function
    at Tab.popToRoot (http://localhost:8100/build/js/app.bundle.js:62664:26)
    at ContactCreated.onUserFormCanceled (http://localhost:8100/build/js/app.bundle.js:75158:19)
```

**For `this.nav.popTo(this.nav.first())`:**
```
TypeError: Cannot read property 'instance' of null
    at http://localhost:8100/build/js/app.bundle.js:62823:70
    at Tab._stage (http://localhost:8100/build/js/app.bundle.js:62874:25)
    at Tab._transition (http://localhost:8100/build/js/app.bundle.js:62818:19)
    at Tab.popTo (http://localhost:8100/build/js/app.bundle.js:62651:19)
    at ContactCreated.onUserFormCanceled (http://localhost:8100/build/js/app.bundle.js:75158:19)
```
Something broken. But "Back" button in navbar is working fine.

Instatiated as:
```
    constructor(
        private params: NavParams,
        private nav: NavController
    ) {
        this.contact = params.get('contact');
    }
```

**Comment by astec** [comment]
Calling directly from template raises same errors.

`<button type="button" (click)="nav.popToRoot()">Navigate back to root</button>`
