### ISSUE TITLE
ionic build ios - TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#522]
```
$ ionic build ios
Error happened [TypeError: Path must be a string. Received undefined]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.bundle (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/build.js:19:32)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:130:22
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
```

The line in question is:
```
  // load webpack config
  var config,
      webPackConfigPath = path.join(options.appDirectory, 'webpack.config.js');
```

If hardcoded fails in other places - seems the options parameter is not passed correctly.
`$  cordova prepare` executing OK.

Ionic: 2.0.0-alpha.22 from NPM as ionic@alpha

Tested with Node: v4.2.2, v5.0.0 & v0.12.7

**Comment by jbavari** [comment]
Fixed in alpha.23 of the CLI.
