### ISSUE TITLE
Tutorial cutePuppyPics not work on Safari 8 & ios7.1

### ISSUE THREAD

**Issue by nvcken** [driftyco/ionic2#525]
I tried simple cutePuppyPics sample from ionic2 homepage.
I run ionic serve.
Seem it work fine on firefox , chrome and ios 9 simulator
But layout break all on Safari 8
![c131f84eed94b16f4b54be83b2f4b4bbffa0fc33_1_679x500](https://cloud.githubusercontent.com/assets/3489866/11167178/ba6e70b0-8b89-11e5-8d83-176592e5efcd.png)
and also iphone 5 - ios 7.1.
![e9d850d2e96b6c2480bea8975592cf17f96e6145](https://cloud.githubusercontent.com/assets/3489866/11167179/c06021a8-8b89-11e5-9f50-e066c88fabd2.png)

**Comment by brandyscarney** [comment]
Thanks for reporting! There is an issue here for this: https://github.com/driftyco/ionic2/issues/516

**Comment by nvcken** [comment]
I read it. Could you make clear?
```
use the same autoprefixer config as the ionic2 repo
```
I can not find gulpfile.js in cutePuppyPics so how can I config autoprefixer same as ionic2 repo.

Thanks

**Comment by brandyscarney** [comment]
That was a comment for us to fix it. It is fixed now when you start a new app, but if you already have an app created you can update your webpack.config.js to this: https://raw.githubusercontent.com/driftyco/ionic2-app-base/master/webpack.config.js

**Comment by nvcken** [comment]
Ok I tried update webpack.config.js and also $ ionic start cutePuppyPics --v2
But both get error below , please take a look 
```
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/nvcken/x.Sample/ionic_group/cutePuppyPics/webpack.config.js

/Users/nvcken/.nvm/versions/node/v5.0.0/lib/~/ionic/~/ionic-app-lib/~/css-loader!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/~/ionic/~/ionic-app-lib/~/autoprefixer/lib/autoprefixer.js?browsers=last 2 version!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/~/ionic/~/ionic-app-lib/~/resolve-url-loader!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/~/ionic/~/ionic-app-lib/~/sass-loader?sourceMap!./www/app/app.scss
Module build failed: CssSyntaxError: /css-loader!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/autoprefixer/lib/autoprefixer.js?browsers=last 2 version!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/resolve-url-loader/index.js!/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/sass-loader/index.js?sourceMap!/Users/nvcken/x.Sample/ionic_group/cutePuppyPics/www/app/app.scss:2:7: Unknown word
    at Input.error (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownWord (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/parser.js:479:26)
    at Parser.word (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (/Users/nvcken/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/css-loader/lib/loader.js:24:2)
 @ ./www/app/app.scss 4:14-597 (CLI v2.0.0-alpha.22)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.31
Ionic CLI Version: 2.0.0-alpha.22
Ionic App Lib Version: 2.0.0-alpha.21
ios-deploy version: Not installed
ios-sim version: 5.0.3
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Xcode 7.0.1 Build version 7A1001
```

**Comment by nvcken** [comment]
It's work when I switch to node v4. so there maybe problem occur on node v5. I make clear for ionic team to check it.
And just small problem 
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-gpnLwpFw97DB28/JjA3G79AHgq5DtCgFiFwjahrA1d4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

app.bundle.js:9431 Platform ready

```
```
Refused to load the image 'https://pbs.twimg.com/profile_images/514549811765211136/9SgAuHeY.png' because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

(index):1 Refused to load the image 'https://avatars3.githubusercontent.com/u/11214?v=3&s=460' because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

```

**Comment by brandyscarney** [comment]
Can you try updating the Ionic CLI? The latest version is 23, when you run `ionic info` you should get this:

```
Ionic CLI Version: 2.0.0-alpha.23
```

To update: `npm install -g ionic@alpha`

**Comment by nvcken** [comment]
Ok it works fine when update lastest ionic CLI
Recently I would keep run ionic cli on node v4.
Node v5 has few error when update -g or update npm itself.
So I think node v4 is more stable.

Thanks for help
