### ISSUE TITLE
CLI: Failing in $  ionic resources --icon

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#577]
```$  ionic resources --icon``` fails. ```$  ionic resources``` works fine. Ionic2 alpha 23.
```
TypeError: Cannot read property 'then' of undefined
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:135:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3


Cannot read property 'then' of undefined (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.1.1 Build version 7B1005
```

**Comment by gigocabrera** [comment]
+1  

Cordova CLI: 5.3.3
Gulp version: CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-alpha.35
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: 
Node Version: v5.1.0

**Comment by tlancina** [comment]
Should be fixed in alpha.24.
