### ISSUE TITLE
Upgrading from 31 to 33 breaking the entire app

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#578]
I have a working Ionic2 app in 31 version but as soon as I upgrade to 33 entire app is broken with destroyed layout I am worried about the upgrade process

**Comment by mpaland** [comment]
"tabs" starter sample doesn't seem to work either on 33.

**Comment by adamdbradley** [comment]
Have you updated both the css and js? Any JS errors?

**Comment by ajaybeniwal** [comment]
No changes to CSS and js no error in console entire UI breaks which was
working fine in 31 I'm really lost

**Comment by mhartington** [comment]
@ajaybeniwal and @mpaland would you both be able to past the output from `ionic info`. I am able to upgrade the tabs project from alpha31 to 33 without any issues, so I'm thinking it has to do with some tooling issues.

```
Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2
ios-sim version: 5.0.3
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.1 Build version 7B91b
```

**Comment by mpaland** [comment]
I'm getting an error for the version info:
```
D:\Visual Studio\Projects\ionic2\conference-app> ionic info

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: Windows 8.1
Node Version: v0.12.7



TypeError: Cannot read property 'then' of undefined
    at Object.run (C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:135:14)
    at Object.<anonymous> (C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


Cannot read property 'then' of undefined (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: Windows 8.1
Node Version: v0.12.7
```
ionic2 starter conference app (and tabs) app are not running:
```
D:\Visual Studio\Projects\ionic2\conference-app> ionic serve
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: D:\Visual Studio\Projects\ionic2\conference-app\webpack.config.js

./~/moment/moment.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/buildin/module.js in D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js]
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js]
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\moment\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts]
 @ ./~/moment/moment.js 1:0-132,./www/app/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/css-loader/index.js in D:\Visual Studio\Projects\ionic2\conference-app\www\app
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js]
 @ ./www/app/app.scss 4:14-553,./www/app/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/style-loader/addStyles.js in D:\Visual Studio\Projects\ionic2\conference-app\www\app
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js]
 @ ./www/app/app.scss 7:13-146,./www/app/map/map.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/css-loader/index.js in D:\Visual Studio\Projects\ionic2\conference-app\www\app\map
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js]
 @ ./www/app/map/map.scss 4:14-553,./www/app/map/map.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/style-loader/addStyles.js in D:\Visual Studio\Projects\ionic2\conference-app\www\app\map
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js]
[D:\Visual Studio\Projects\ionic2\conference-app\www\app\map\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts]
 @ ./www/app/map/map.scss 7:13-146,./~/ionic-framework/~/@reactivex/rxjs/dist/cjs/util/root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/Marco/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/buildin/module.js in D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util
resolve file
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js doesn't exist
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts doesn't exist
resolve directory
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist (directory default file)
  D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js\package.json doesn't exist (directory description file)
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js]
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js]
[D:\Visual Studio\Projects\ionic2\conference-app\node_modules\ionic-framework\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\Marco\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts]
 @ ./~/ionic-framework/~/@reactivex/rxjs/dist/cjs/util/root.js 1:0-132 (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: Windows 8.1
Node Version: v0.12.7
```

After an update via "npm -g update", ionic2 alpha is getting lost:
 D:\Visual Studio\Projects\ionic2\conference-app> ionic info

Your system information:
```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
OS: Windows 8.1
Node Version: v0.12.7
```

Tested on Windows.

**Comment by mhartington** [comment]
the `.then` error is known and being fixed. 

The other error is with moment.js, which was resolved here

https://github.com/driftyco/ionic-conference-app/issues/62

The conference app was updated, so you're best off doing a fresh install from there.

But the ionic info output brings up some other question, as it reports two different versions of the cli

So may be best to to the following

```bash
# install the latest cli
npm install -g ionic@alpha
# clone the main conference app
git clone https://github.com/driftyco/ionic-conference-app.git
cd ionic-conference-app
npm install
ionic serve
```
You should be caught up with that.

**Comment by mpaland** [comment]
Mike, thanx for looking into it!
Your steps are exactly the steps I did 15 minutes ago - with the results above.
Maybe there's another problem with my installation... I try to start over once again.

**Comment by mhartington** [comment]
Possibly. I have the alpha cli up and running on a windows machine myself and have not run into these issues.

**Comment by tlancina** [comment]
@mpaland looks like your project is on D: and your node install is on C: and you're running into https://github.com/driftyco/ionic2/issues/528

**Comment by ajaybeniwal** [comment]
My information is 
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: Windows 7 SP1
Node Version: v4.2.1



TypeError: Cannot read property 'then' of undefined
    at Object.run (C:\Users\ajasingh\AppData\Roaming\nvm\v4.2.1\node_modu
ic\lib\cli.js:135:14)
    at Object.<anonymous> (C:\Users\ajasingh\AppData\Roaming\nvm\v4.2.1\n
ules\ionic\bin\ionic:9:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3


Cannot read property 'then' of undefined (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.33
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS: Windows 7 SP1
Node Version: v4.2.1
