### ISSUE TITLE
CLI error on ionic info

### ISSUE THREAD

**Issue by patrickpereira** [driftyco/ionic2#618]
$ ionic info

Your system information:

Cordova CLI: 5.2.0
Ionic Version: 2.0.0-alpha.35
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C46t 

TypeError: Cannot read property 'then' of undefined
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:135:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Cannot read property 'then' of undefined (CLI v2.0.0-alpha.23)

**Comment by tlancina** [comment]
Should be fixed in alpha.24 of the CLI.
