### ISSUE TITLE
Radio buttons broken in Alpha 37

### ISSUE THREAD

**Issue by jwbuitenhuis** [driftyco/ionic2#673]
Since Alpha 37 I'm getting an error related to:

    <ion-radio-group>
      <ion-radio (click)="changeType(0)" [checked]="type === 0">
        Per day
      </ion-radio>
      <ion-radio (click)="changeType(1)" [checked]="type === 1">
        Per hour
      </ion-radio>
      <ion-radio (click)="changeType(2)" [checked]="type === 2">
        Per year
      </ion-radio>
    </ion-radio-group>

Exception:

EXCEPTION: TypeError: Cannot read property 'registerRadio' of null in [null]
app.bundle.js:54649 EXCEPTION: TypeError: Cannot read property 'registerRadio' of null in [null]BrowserDomAdapter.logError @ app.bundle.js:54649BrowserDomAdapter.logGroup @ app.bundle.js:54659ExceptionHandler.call @ app.bundle.js:16601(anonymous function) @ app.bundle.js:49797NgZone._notifyOnError @ app.bundle.js:45687errorHandling.onError @ app.bundle.js:45585run @ app.bundle.js:8615(anonymous function) @ app.bundle.js:45600NgZone.run @ app.bundle.js:45549(anonymous function) @ app.bundle.js:49883schedulerFn @ app.bundle.js:19379tryCatcher @ app.bundle.js:20432next @ app.bundle.js:20341_next @ app.bundle.js:26769next @ app.bundle.js:26730(anonymous function) @ app.bundle.js:45442run @ app.bundle.js:8612NgZone._notifyOnTurnDone @ app.bundle.js:45442(anonymous function) @ app.bundle.js:45614zoneBoundFn @ app.bundle.js:8585lib$es6$promise$$internal$$tryCatch @ app.bundle.js:1117lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:1127lib$es6$promise$$internal$$publish @ app.bundle.js:1103lib$es6$promise$asap$$flush @ app.bundle.js:922
app.bundle.js:54649 ORIGINAL EXCEPTION: TypeError: Cannot read property 'registerRadio' of nullBrowserDomAdapter.logError @ app.bundle.js:54649ExceptionHandler.call @ app.bundle.js:16610(anonymous function) @ app.bundle.js:49797NgZone._notifyOnError @ app.bundle.js:45687errorHandling.onError @ app.bundle.js:45585run @ app.bundle.js:8615(anonymous function) @ app.bundle.js:45600NgZone.run @ app.bundle.js:45549(anonymous function) @ app.bundle.js:49883schedulerFn @ app.bundle.js:19379tryCatcher @ app.bundle.js:20432next @ app.bundle.js:20341_next @ app.bundle.js:26769next @ app.bundle.js:26730(anonymous function) @ app.bundle.js:45442run @ app.bundle.js:8612NgZone._notifyOnTurnDone @ app.bundle.js:45442(anonymous function) @ app.bundle.js:45614zoneBoundFn @ app.bundle.js:8585lib$es6$promise$$internal$$tryCatch @ app.bundle.js:1117lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:1127lib$es6$promise$$internal$$publish @ app.bundle.js:1103lib$es6$promise$asap$$flush @ app.bundle.js:922
app.bundle.js:54649 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ app.bundle.js:54649ExceptionHandler.call @ app.bundle.js:16613(anonymous function) @ app.bundle.js:49797NgZone._notifyOnError @ app.bundle.js:45687errorHandling.onError @ app.bundle.js:45585run @ app.bundle.js:8615(anonymous function) @ app.bundle.js:45600NgZone.run @ app.bundle.js:45549(anonymous function) @ app.bundle.js:49883schedulerFn @ app.bundle.js:19379tryCatcher @ app.bundle.js:20432next @ app.bundle.js:20341_next @ app.bundle.js:26769next @ app.bundle.js:26730(anonymous function) @ app.bundle.js:45442run @ app.bundle.js:8612NgZone._notifyOnTurnDone @ app.bundle.js:45442(anonymous function) @ app.bundle.js:45614zoneBoundFn @ app.bundle.js:8585lib$es6$promise$$internal$$tryCatch @ app.bundle.js:1117lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:1127lib$es6$promise$$internal$$publish @ app.bundle.js:1103lib$es6$promise$asap$$flush @ app.bundle.js:922
app.bundle.js:54649 TypeError: Cannot read property 'registerRadio' of null
    at RadioButton.onInit (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:77054:24)
    at AbstractChangeDetector.ChangeDetector_RatePage_0.detectChangesInRecordsInternal (eval at <anonymous> (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:38511:17), <anonymous>:128:99)
    at AbstractChangeDetector.detectChangesInRecords (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37504:19)
    at AbstractChangeDetector.runDetectChanges (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37481:15)
    at AbstractChangeDetector._detectChangesInViewChildren (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37573:19)
    at AbstractChangeDetector.runDetectChanges (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37485:15)
    at AbstractChangeDetector._detectChangesContentChildren (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37566:19)
    at AbstractChangeDetector.runDetectChanges (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37482:15)
    at AbstractChangeDetector._detectChangesInViewChildren (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37573:19)
    at AbstractChangeDetector.runDetectChanges (https://clients.elevatedirect.com/Elevate.Native.Contractors/www/build/js/app.bundle.js:37485:15)BrowserDomAdapter.logError @ app.bundle.js:54649ExceptionHandler.call @ app.bundle.js:16614(anonymous function) @ app.bundle.js:49797NgZone._notifyOnError @ app.bundle.js:45687errorHandling.onError @ app.bundle.js:45585run @ app.bundle.js:8615(anonymous function) @ app.bundle.js:45600NgZone.run @ app.bundle.js:45549(anonymous function) @ app.bundle.js:49883schedulerFn @ app.bundle.js:19379tryCatcher @ app.bundle.js:20432next @ app.bundle.js:20341_next @ app.bundle.js:26769next @ app.bundle.js:26730(anonymous function) @ app.bundle.js:45442run @ app.bundle.js:8612NgZone._notifyOnTurnDone @ app.bundle.js:45442(anonymous function) @ app.bundle.js:45614zoneBoundFn @ app.bundle.js:8585lib$es6$promise$$internal$$tryCatch @ app.bundle.js:1117lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:1127lib$es6$promise$$internal$$publish @ app.bundle.js:1103lib$es6$promise$asap$$flush @ app.bundle.js:922
app.bundle.js:54649 ERROR CONTEXT:BrowserDomAdapter.logError @ app.bundle.js:54649ExceptionHandler.call @ app.bundle.js:16617(anonymous function) @ app.bundle.js:49797NgZone._notifyOnError @ app.bundle.js:45687errorHandling.onError @ app.bundle.js:45585run @ app.bundle.js:8615(anonymous function) @ app.bundle.js:45600NgZone.run @ app.bundle.js:45549(anonymous function) @ app.bundle.js:49883schedulerFn @ app.bundle.js:19379tryCatcher @ app.bundle.js:20432next @ app.bundle.js:20341_next @ app.bundle.js:26769next @ app.bundle.js:26730(anonymous function) @ app.bundle.js:45442run @ app.bundle.js:8612NgZone._notifyOnTurnDone @ app.bundle.js:45442(anonymous function) @ app.bundle.js:45614zoneBoundFn @ app.bundle.js:8585lib$es6$promise$$internal$$tryCatch @ app.bundle.js:1117lib$es6$promise$$internal$$invokeCallback @ app.bundle.js:1127lib$es6$promise$$internal$$publish @ app.bundle.js:1103lib$es6$promise$asap$$flush @ app.bundle.js:922
app.bundle.js:54649 _Context {element: ion-radio.item, componentElement: ion-page, context: RatePage, locals: Object, injector: Injector…}

**Comment by brandyscarney** [comment]
Hey, the syntax was changed with alpha.37. It should change to this:

```
  <ion-list radio-group>
    <ion-radio (click)="changeType(0)" [checked]="type === 0">
      Per day
    </ion-radio>
    <ion-radio (click)="changeType(1)" [checked]="type === 1">
      Per hour
    </ion-radio>
    <ion-radio (click)="changeType(2)" [checked]="type === 2">
      Per year
    </ion-radio>
  </ion-list>
```

Please see this file for some more examples: https://github.com/driftyco/ionic2/blob/master/ionic/components/radio/test/basic/main.html
