### ISSUE TITLE
Problems with NgFor

### ISSUE THREAD

**Issue by mrkaspa** [driftyco/ionic2#709]
I'm following this guide and doing the example http://www.joshmorony.com/build-a-todo-app-from-scratch-with-ionic-2-video-tutorial/ , I think the error is with the binding and the ngFor directive

I get this error in the browser when loading the records from the database Error trying to diff '[object Object]' in [null], this is the full trace Error:

```
Error trying to diff '[object Object]'

at new BaseException (http://localhost:8100/build/js/app.bundle.js:26208:24)

at DefaultIterableDiffer.diff (http://localhost:8100/build/js/app.bundle.js:28413:20)

at NgFor.doCheck (http://localhost:8100/build/js/app.bundle.js:41023:41)

at AbstractChangeDetector.ChangeDetector_ListPage_0.detectChangesInRecordsInternal (eval at <anonymous> (http://localhost:8100/build/js/app.bundle.js:33077:17), <anonymous>:62:48)

at AbstractChangeDetector.detectChangesInRecords (http://localhost:8100/build/js/app.bundle.js:32421:19)

at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:32398:15)

at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:8100/build/js/app.bundle.js:32490:19)

at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:32402:15)

at AbstractChangeDetector._detectChangesContentChildren (http://localhost:8100/build/js/app.bundle.js:32483:19)

at AbstractChangeDetector.runDetectChanges (http://localhost:8100/build/js/app.bundle.js:32399:15)
```

**Comment by tarolechaitanya** [comment]
Even I am facing the same issue.
Using (change) on 'select' not working in ionic 2

**Comment by Luchillo** [comment]
Have you ensured that the `items` array exist?, even if it is an empty array?
