### ISSUE TITLE
(gulp src) Error: Task transpile.common is not configured as a task on gulp

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#722]
Started to get an error on building sources from master:

```
ionic2_git astec$ gulp src
[02:08:57] Warning: gulp version mismatch:
[02:08:57] Global gulp is 3.9.0
[02:08:57] Local gulp is 3.8.11
[02:08:58] Using gulpfile ~/ionic2_git/gulpfile.js
[02:08:58] Starting 'src'...
[02:08:58] 'src' errored after 738 μs
[02:08:58] Error: Task transpile.common is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at /Users/astec/ionic2_git/node_modules/run-sequence/index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (/Users/astec/ionic2_git/node_modules/run-sequence/index.js:13:11)
    at runSequence (/Users/astec/ionic2_git/node_modules/run-sequence/index.js:94:2)
    at Gulp.<anonymous> (/Users/astec/ionic2_git/gulpfile.js:417:3)
    at module.exports (/Users/astec/ionic2_git/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/astec/ionic2_git/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/astec/ionic2_git/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/astec/ionic2_git/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
```
CC @tlancina

**Comment by tlancina** [comment]
@astec can you pull master? I just updated the `src` task.

Just a heads up things are going to be breaking for the next day or so as we switch things over to typescript and the new package structure.

**Comment by astec** [comment]
@tlancina, Thanks,the gulp step is fixed now.

Just wanted to let you know the `ionic serve` stopped to work:
```
$ ionic serve
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/astec/MyPetProject/ionic_app/webpack.config.js 

./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/astec/MyPetProject/ionic_app/www/app
    Required in /Users/astec/MyPetProject/ionic_app/www/app/my-app.ts
 @ multi main (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.40
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68 
```

where app.js is:
```
import {MyApp} from './my-app.ts';
export MyApp;
```
And `my-app.ts` is like:
```
import {App, Platform, StatusBar, Modal, Page, NavController, Modal} from 'ionic/ionic';
...
```

Are there some changes needed to the project files as well? webpack.config?

**Comment by tlancina** [comment]
Try changing the import to `ionic-framework/ionic`, until https://github.com/Microsoft/TypeScript/issues/5039 typescript can only find the module exactly as it's named in `node_modules` I believe.

**Comment by astec** [comment]
Did not work.
```
$ ionic serve
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/astec/MyPetProject/ionic_app/webpack.config.js 

./www/app/app.js
Module build failed: Cannot resolve module 'ionic-famework/ionic' in /Users/astec/MyPetProject/ionic_app/www/app
    Required in /Users/astec/MyPetProject/ionic_app/www/app/my-app.ts
 @ multi main (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.40
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by tlancina** [comment]
`Cannot resolve module 'ionic-famework/ionic'`, looks like you named it `ionic-famework`, not `ionic-framework` :)

**Comment by astec** [comment]
Yeah, Ionic is famous. Anyway `ionic-framework` does not work either.

**Comment by astec** [comment]
I've tried to move my code to Ionic conference app which compiles & work just fine.

But it uses .JS and if I try to use my `.ts` files it fails to compile with errors like:

```
./www/app/data.ts
Module parse failed: /Users/astec/MyPetProject/ionic2_app/www/app/data.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {Injectable} from "angular2/angular2";
```

**Comment by brandyscarney** [comment]
Have you tried using the Typescript branch:

https://github.com/driftyco/ionic-conference-app/tree/typescript

**Comment by astec** [comment]
@brandyscarney Thanks Brandy! You've made my day. Everything is working now and even IDE started recognize Ionic typings.

**Comment by brandyscarney** [comment]
Awesome! Glad it's working. :)
