### ISSUE TITLE
Problems with new project template

### ISSUE THREAD

**Issue by mrkaspa** [driftyco/ionic2#732]
After using the new template #730 now I get these errors with a new blank project

```
~/code/js/ionic-model/ gulp sass watch
[17:12:23] Using gulpfile ~/code/js/ionic-model/gulpfile.js
[17:12:23] Starting 'sass'...
[17:12:23] 'sass' errored after 392 ms
[17:12:23] TypeError: Cannot read property 'appSassSrc' of undefined
    at Gulp.<anonymous> (/Users/michelperez/code/js/ionic-model/gulpfile.js:41:15)
    at module.exports (/Users/michelperez/code/js/ionic-model/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/michelperez/code/js/ionic-model/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/michelperez/code/js/ionic-model/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/michelperez/code/js/ionic-model/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
```

```
~/code/js/ionic-model/ ionic serve
∆ Compiling and bundling with Webpack...
There was an error loading webpack.config.js:

TypeError: Cannot read property 'wwwDir' of undefined
    at Object.<anonymous> (/Users/michelperez/code/js/ionic-model/webpack.config.js:11:31)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.bundle (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/build.js:23:14)
    at Object.serve (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/serve.js:26:30)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:85:20


Cannot read property 'wwwDir' of undefined (CLI v2.0.0-alpha.25)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v4.1.0
Xcode version: Xcode 7.1.1 Build version 7B1005
```

**Comment by brandyscarney** [comment]
Does the `ionic.config` file have these values? https://github.com/driftyco/ionic-conference-app/blob/master/ionic.config.js#L19-L31

**Comment by mrkaspa** [comment]
I got this:

```js

module.exports = {
  name: 'ionic-model',
  proxies: null,

  // hooks execute before or after all project-related Ionic commands
  // (so not for start, docs, but serve, run, etc.) and take in the arguments
  // passed to the command as a parameter
  //
  // The format is 'before' or 'after' + commandName (uppercased)
  // ex: beforeServe, afterRun, beforePrepare, etc.
  hooks: {
    // beforeServe: function(argv) {
    //   console.log('Arguments to ionic serve: "' + argv._ + '"');
    // }
  }
}

```

**Comment by brandyscarney** [comment]
Oh. Please update the CLI to the beta version: `npm install -g ionic@beta` then try creating a new project.

**Comment by mrkaspa** [comment]
Great in the doc the library is still en alpha http://ionicframework.com/docs/v2/getting-started/installation/ , thank you so much

**Comment by brandyscarney** [comment]
Thank you for letting us know! We'll get that updated. https://github.com/driftyco/ionic2/issues/733
