### ISSUE TITLE
Webpack Config Paths

### ISSUE THREAD

**Issue by kevineaton** [driftyco/ionic2#736]
I started with afresh install on a new MacBook Pro. Followed the tutorial changed into the directory, and ran 

ionic serve

Received the following error:
```
ionic serve
∆ Compiling and bundling with Webpack...
There was an error loading webpack.config.js:

TypeError: Cannot read property 'wwwDir' of undefined
    at Object.<anonymous> (/Users/kevineaton/dev/projects/kdojang/mobile/webpack.config.js:11:31)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.bundle (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/build.js:23:14)
    at Object.serve (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/serve.js:26:30)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:85:20


Cannot read property 'wwwDir' of undefined (CLI v2.0.0-alpha.25)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Not installed

```

The webpack config is including an ionic.config.js file and looking for the paths property which does not exist. The ionic.config.js file contains:
```
module.exports = {
  name: 'mobile',
  proxies: null,

  // hooks execute before or after all project-related Ionic commands
  // (so not for start, docs, but serve, run, etc.) and take in the arguments
  // passed to the command as a parameter
  //
  // The format is 'before' or 'after' + commandName (uppercased)
  // ex: beforeServe, afterRun, beforePrepare, etc.
  hooks: {
    // beforeServe: function(argv) {
    //   console.log('Arguments to ionic serve: "' + argv._ + '"');
    // }
  }
}
```

**Comment by brandyscarney** [comment]
Please update to the latest CLI (beta): `npm install -g ionic@beta`

http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by kevineaton** [comment]
Hello @brandyscarney Unfortunately there was a conflict in upgrading, so I had to completely remove the ionic installation and reinstall ionic with the beta tag. That seemed to have fixed it, so thanks.

However, shouldn't the docs be updated at http://ionicframework.com/docs/v2/getting-started/installation/   which says to use the @alpha branch?

**Comment by brandyscarney** [comment]
Where do you see that? I don't see alpha branch anywhere.

**Comment by kevineaton** [comment]
Very strange. Hard refresh and it now shows @beta although I hadn't visited that page before. Seems fine now. Thanks for the help!

**Comment by brandyscarney** [comment]
That is strange, but glad you have it working. :)

**Comment by herve1976** [comment]
same issue here
