### ISSUE TITLE
Angular 2 HTTP works in browser and iOS, but errors in Android

### ISSUE THREAD

**Issue by nraboy** [driftyco/ionic2#781]
When trying to make a simple HTTP request in Android, I get the following error:

```
I/chromium( 2023): [INFO:CONSOLE(36427)] "EXCEPTION: SyntaxError: Unexpected end of input", source: file:///android_asset/www/build/js/app.bundle.js (36427)
I/chromium( 2023): [INFO:CONSOLE(36427)] "STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (36427)
I/chromium( 2023): [INFO:CONSOLE(36427)] "SyntaxError: Unexpected end of input
I/chromium( 2023):     at Object.parse (native)
I/chromium( 2023):     at Function.Json.parse (file:///android_asset/www/build/js/app.bundle.js:8040:54)
I/chromium( 2023):     at Response.json (file:///android_asset/www/build/js/app.bundle.js:29677:41)
I/chromium( 2023):     at Subscriber._error (file:///android_asset/www/build/js/app.bundle.js:62338:47)
I/chromium( 2023):     at Subscriber.error (file:///android_asset/www/build/js/app.bundle.js:19026:19)
I/chromium( 2023):     at XMLHttpRequest.onLoad (file:///android_asset/www/build/js/app.bundle.js:29560:35)
I/chromium( 2023):     at Zone.run (file:///android_asset/www/build/js/app.bundle.js:5051:18)
I/chromium( 2023):     at Zone.run (file:///android_asset/www/build/js/app.bundle.js:20323:43)
I/chromium( 2023):     at XMLHttpRequest.zoneBoundFn (file:///android_asset/www/build/js/app.bundle.js:5024:20)", source: file:///android_asset/www/build/js/app.bundle.js (36427)
I/chromium( 2023): [INFO:CONSOLE(10755)] "Uncaught SyntaxError: Unexpected end of input", source: file:///android_asset/www/build/js/app.bundle.js (10755)
```

Here is the code that I'm running:

```
import {Page, Platform, Popup} from 'ionic/ionic';
import {Http} from 'angular2/http';

@Page({
    templateUrl: 'app/home/home.html',
})

export class HomePage {
    constructor(platform: Platform, http: Http, popup: Popup) {
        this.platform = platform;
        this.http = http;
        this.popup = popup;
    }

    makeGetRequest() {
        this.http.get("https://httpbin.org/ip")
        .subscribe(data => {
            this.popup.alert({
                title: "Your IP Address",
                template: data.json().origin,
                cssClass: "my-alert"
            });
        }, error => {
            console.log(JSON.stringify(error.json()));
        });
    }
}
```

Now this works fine with iOS and fine in the browser.

Any ideas?

Thanks,

**Comment by mhartington** [comment]
Ionic info out put plus the version of android you tested.
Unable to reproduce on android 6x or 5x

**Comment by nraboy** [comment]
```
macbookpro:Desktop nraboy$ ionic info

Your system information:

Cordova CLI: 5.4.1
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 
```

I am using Genymotion's Nexus 4 API 22 (5.1) image.

**Comment by mhartington** [comment]
This is not from inside your project folder. 
Please run it there.

**Comment by nraboy** [comment]
```
Raboy-iMac:ExampleProject nraboy$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68
```

Better?

**Comment by mhartington** [comment]
Used a genymotion image and the same code, still not able to reproduce.

```js
import {Page, Platform, Popup} from 'ionic/ionic';
import {Http} from 'angular2/http';
@Page({
  templateUrl: 'app/home/home.html',
})
export class HomePage {
  constructor(platform: Platform, http: Http, popup: Popup) {
    this.platform = platform;
    this.http = http;
    this.popup = popup;
    this.makeGetRequest();
  }
  makeGetRequest() {
    this.http.get("https://httpbin.org/ip")
      .subscribe(data => {
        this.popup.alert({
          title: "Your IP Address",
          template: data.json().origin,
          cssClass: "my-alert"
        });
      }, error => {
        console.log(JSON.stringify(error.json()));
      });
  }
}
```

```bash
ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.1 Build version 7B91b
```

**Comment by nraboy** [comment]
So now what?

Got anyone else that can try it?

**Comment by mhartington** [comment]
Can get someone to test this Monday. 
How were you calling that method? 

Mike Hartington

**Comment by nraboy** [comment]
```
<button (click)="makeGetRequest()">Request</button>
```

**Comment by 3dd13** [comment]
I guess it is something about the https and the SSL certificate
@nraboy could you check by sending request to __http__://httpbin.org/ip instead of __https__://httpbin.org/ip

**Comment by ivanbtrujillo** [comment]
@nraboy on my nexus 5 with android 6.1 works fine.
![alt tag](https://dl.dropboxusercontent.com/u/16022161/Screenshot_20151221-095331.png)
Here's my Ionic info:

```
ivanbtrujillo@MacBookPro: ~/Ionic2Projects/MyClipboard[2c99679]  9:53
> ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v1.5.1
Xcode version: Xcode 7.0.1 Build version 7A1001
```

And here my device info:
![alt tag](https://dl.dropboxusercontent.com/u/16022161/Screenshot_20151221-095624.png)

i have copied and pasted your code, and have associated the makeGetRequest function to the red button that you can see on the screenshot.
```
<button danger fab fab-left fab-bottom (click)="makeGetRequest()"><icon cloud-download></icon></button>
```
Maybe is your genymotion config?

**Comment by mhartington** [comment]
@3dd13 I don't think it's an http/https issue since the original code posted works fine.

**Comment by nraboy** [comment]
I appreciate everyone testing.  The solution was actual what @ivanbtrujillo said.

My Genymotion image was corrupt or something.  I wiped it out and downloaded a fresh one and it worked after that.

@mhartington I guess in the probably small percentage of people who suffer from this like I did, point them to refreshing their Genymotion images.

Thanks,

**Comment by mhartington** [comment]
:+1:
