### ISSUE TITLE
Inline constructor broken since update on 22/12/2015

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#801]
Hi, before i updated i had something like this:
>     export class Config {
    constructor(
      private popup: Popup,
      public db: DB
    ) {
      var this_ref = this;
      ...

Now i'm forced to write it like this because the error:
>     export class Config {
      constructor(
        popup: Popup,
        db: DB
      ) {
        this.popup = popup;
        this.db = db;
        ...
Here's the error:
>     ./app/services/config.js
    Module build failed: SyntaxError: /home/carlos/Carlos/Programming/OSGroup/taoappionic2/app/services/config.js: Unexpected token     (9:12)
       7 | export class Config {
       8 |   constructor(
    >  9 |     private popup: Popup,
         |             ^
      10 |     public db: DB
      11 |   ) {
      12 |     var this_ref = this;
    at Parser.pp.raise (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/util.js:85:33)
    at Parser.parseBindingList (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babel-plugin-angular2-annotations/lib/patch.js:27:14)
    at Parser.pp.parseMethod (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/expression.js:853:22)
    at Parser.parseClassMethod (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/plugins/flow.js:859:12)
    at Parser.pp.parseClassBody (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/statement.js:748:10)
    at Parser.pp.parseClass (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/statement.js:631:8)
    at Parser.pp.parseStatement (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/parser/statement.js:95:19)
    at Parser.parseStatement (/home/carlos/Carlos/Programming/OSGroup/taoappionic2/node_modules/babylon/lib/plugins/flow.js:636:22)
    @ ./app/app.js 11:14-42,./app/services/db.js

**Comment by mhartington** [comment]
Looks like you were trying to use typescript styled code in a javascript file. We've switch webpack loaders recently, from typescript (without type checking) to babel.

https://github.com/driftyco/ionic2-app-base/blob/master/webpack.config.js#L22


For typescript, you need to use a different loader

https://github.com/driftyco/ionic2-app-base/blob/typescript/webpack.config.js#L21

**Comment by Luchillo** [comment]
Oh so babel doesn't support typescript? only ES2015?

**Comment by mhartington** [comment]
Unfortunately it does not.

**Comment by Luchillo** [comment]
Care to explain why the change?

**Comment by tlancina** [comment]
@Luchillo the Typescript compiler offers type-checking, which is great and adds a lot of benefits, but comes at the cost of additional speed and complexity at times.  Also, we found that trying to have a single setup that could handle both ES2015/ES6 and Typescript was probably more confusing for new users than just having a dedicated setup for each one.  Babel is the best tool for transpiling ES2015/ES6, so there's no reason to not use it if that's what your app is written in.  The reason we didn't do so from the beginning is because there were some issues getting it to work with some of Angular's decorators used for DI, but those have been resolved thanks to updates to https://github.com/shuhei/babel-plugin-angular2-annotations.

You can still use typescript in your project with the `--ts` flag for starters: `ionic start myapp --v2 --ts`.  This will download .ts files by default, and ships with a webpack config that is setup for transpiling typescript.  Type checking is still optional, and can be toggled on or off in your webpack config file.

**Comment by Luchillo** [comment]
Cool, i think i will have to go with ts config with ES6 code, as the js version for some reason is broken in my ubuntu 15.10, i'm unable to compile to android, nor even the sidemenu starter does.

No need to reply as i filled an issue already in: https://github.com/driftyco/ionic2/issues/805
